name: Anchore Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile --tag testrepo/testimage9:latest
    - uses: anchore/scan-action@v1
      with:
        image-reference: "testrepo/testimage9:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: false
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AnchoreReports
        path: ./anchore-reports/
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: naveenr211
          password: c68671f2-540c-400e-a17a-d2bb6305a5a9
    -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: naveenr211/anchor-jenkins:testimage9
